[settings]
barpad = 1
barsperline = 0
basslabels = "tuning"
beatsnap = "soft"
charstyle = "standard"
chordwrap = 0
contrast = "high"
countdots = "off"
dotplacement = "afterflag"
duetscoreview = "auto"
flaglean = "right"
flagredundant = "on"
flagstems = "single"
flagstyle = "standard"
fontstyle = "modern"
frenchc = "normal"
fretlabelmode = "auto"
ft3fingering = "both"
ft3ornaments = "both"
glisscuestyle = "hide"
grid = "off"
holdcuestyle = "angle"
italianmultifret = "on"
italianorient = "normal"
justify = "smart"
key = "C"
keys = "vim+arrows"
layout = "auto"
linelen = 0
lynoteheads = "classic"
maxbars = 0
maxrepeats = 30
maxstretch = 0
measures = "system"
measuresstep = 10
midigate = 85
midipatch = 24
midivocalpatch = 53
minimumfret = 0
movementmode = "visual"
multifretspacing = "collision-safe"
newbars = 8
playbackscroll = "on"
restrainopenstrings = "off"
scrollmode = "smooth"
showdur = "off"
showextras = "off"
showfingerings = "on"
showft3extras = "on"
showlyrics = "on"
lyricmode = "first"
lyricverse = 1
scoreview = "score"
showmelody = "on"
showornaments = "on"
showspans = "off"
showtactus = "off"
showtuning = "on"
showtuplets = "off"
slurcuestyle = "paren"
soundfont = ""
spacing = 10
staffthick = 1
strings = 6
style = "french"
tabnotation = "minimal"
tempo = 60
tiecuestyle = "bracket"
tienoteheads = "show"
time = "3/4"
timesigstyle = "symbol"
tuning = "g2c3f3a3d4g4"
tuninglabels = "relative"
viewinvert = "off"
vocalpos = "bottom"
