[settings]
charstyle = "standard"
countdots = "off"
flagredundant = "on"
flagstyle = "thin"
fontstyle = "modern"
frenchc = "normal"
frenche = "normal"
grid = "off"
italianorient = "normal"
key = "C"
keys = "vim+arrows"
linelen = 80
maxbars = 0
measures = "five"
measuresstep = 1
midigate = 85
midipatch = 24
showdur = "off"
showextras = "off"
showtactus = "off"
soundfont = "/Users/s/Library/Audio/Sounds/Banks/SC-55 SoundFont v1.2b.sf2"
spacing = 12
spacingmode = "packed"
staffthick = 1
strings = 6
style = "french"
tempo = 90
time = "C"
tuning = "g2c3f3a3d4g4"
tuninglabels = "relative"
