[settings]
barpad = 1
barsperline = 0
basslabels = "tuning"
charstyle = "standard"
countdots = "off"
flagredundant = "on"
flagstems = "double"
flagstyle = "standard"
fontstyle = "modern"
frenchc = "normal"
frenchcshape = "normal"
grid = "off"
italianmultifret = "on"
italianorient = "normal"
key = "C"
keys = "vim+arrows"
linelen = 0
maxbars = 0
maxrepeats = 30
measures = "every"
measuresstep = 10
midigate = 85
midipatch = 24
showdur = "on"
showextras = "off"
showtactus = "off"
showtuning = "on"
soundfont = "/Users/s/Library/Audio/Sounds/Banks/SC-55 SoundFont v1.2b.sf2"
spacing = 10
spacingfill = "smart"
spacingmode = "auto"
staffthick = 1
strings = 6
style = "french"
tempo = 55
time = "O"
tuning = "g2c3f3a3d4g4"
tuninglabels = "relative"
viewinvert = "off"
