line-length = 100
target-version = "py311"

[lint]
select = [
  "C90",
  "E",
  "F",
  "I",
  "B",
  "C4",
  "ERA",
  "A",
  "ARG",
  "COM",
  "DTZ",
  "FBT",
  "G",
  "ISC",
  "N",
  "PERF",
  "PIE",
  "PTH",
  "S",
  "PL",
  "RUF",
  "RET",
  "TID",
  "TRY",
  "UP",
  "SIM",
]
ignore = [
  "FBT",
  "PLR0913",
  "PLR0915",
  "PLR2004",
  "S101",
]

[lint.per-file-ignores]
"tests/*" = ["E501", "S101", "PLR2004"]
