from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from oud.importers.tab_syntax import (
    BASS_POSITION,
    FLAG_MODIFIERS,
    POSITIONS,
    TREBLE_POSITIONS,
    read_tuning,
    scientific_to_tuning,
)
from petrucci.core.model import Bar, Piece
from petrucci.input.tablature.input import editor_event_columns, editor_fret_at, editor_rest_at
from petrucci.rendering.primitives.utils import (
    bar_cells,
    bar_cells_from_chords,
    chord_positions,
    flag_positions_from_durations,
    flag_row,
    note_type_to_denom,
)


class TabExportError(ValueError):
    """Raised when the TAB format cannot hold part of the piece."""

    def __init__(self, what: str, value: int) -> None:
        super().__init__(f"TAB cannot hold {what} {value}; save as MusicXML instead")


# Written in the original `tab` program's syntax (docs/tab-format.md). The
# header must differ from Oud's earlier `% Generated by oud`, which marks the
# earlier dialect on read.
HEADER = "% Written by oud"
ITALIAN_SETTING = "$numstyle=italian"
_FRENCH_LETTERS = "abcdefghiklmnop"  # frets 0-14; the program reads j as k
_HIGH_FRET_RANGE = range(10, 31)
_ITALIAN_TEN = "!x"
_ITALIAN_TEN_FRET = 10
_BASS_DIGITS = {11: "4", 12: "5", 13: "6"}
_MAX_BASS_SLASHES = 5
_PLACE_MARKER = "-"
_DEFAULT_BARS_PER_SYSTEM = 4
_SECOND_BASS = "a second bass course in one chord, course"


@dataclass(frozen=True, slots=True)
class _TabExportContext:
    piece: Piece
    overrides: dict[tuple[int, int, int], str]
    durations: dict[tuple[int, int, int], int]
    bar_width: int
    settings: dict[str, str]
    dotted: set[tuple[int, int]]
    style: str
    french_c: str
    default_duration: int = 4

    @property
    def italian(self) -> bool:
        return self.style == "italian"


def _time_signature_line(value: str | None) -> str | None:
    if not value:
        return None
    text = value.strip()
    if text == "C":
        return "SC"
    if text == "C|":
        return "Sc"
    numerator, slash, denominator = text.partition("/")
    if not slash:
        return f"S{text}"
    # Two single digits are the program's plain form; longer ones need its dash form.
    if len(numerator) == 1 and len(denominator) == 1:
        return f"S{numerator}{denominator}"
    return f"S{numerator}-{denominator}"


def _french_to_fret(ch: str) -> int | None:
    if ch == "r":
        return 2
    if "a" <= ch <= "p":
        return ord(ch) - ord("a")
    return None


def _denom_for_column(context: _TabExportContext, bar_index: int, column: int) -> int:
    found = None
    for string_index in range(context.piece.strings):
        duration = context.durations.get((bar_index, string_index, column))
        if duration is not None and (found is None or duration > found):
            found = duration
    return found if found is not None else context.default_duration


def _denom_to_flag(denom: int) -> str:
    return {
        1: "W",
        2: "w",
        4: "0",
        8: "1",
        16: "2",
        32: "3",
        64: "4",
        128: "5",
    }.get(denom, "0")


def _fret_text(fret: int, *, italian: bool) -> str:
    if italian and fret < _ITALIAN_TEN_FRET:
        return str(fret)
    if italian and fret == _ITALIAN_TEN_FRET:
        return _ITALIAN_TEN
    if not italian and 0 <= fret < len(_FRENCH_LETTERS):
        return _FRENCH_LETTERS[fret]
    if fret in _HIGH_FRET_RANGE:
        return f"N{fret}"
    raise TabExportError("fret", fret)


def _bass_text(course: int, fret: int) -> str:
    if fret == 0 and course in _BASS_DIGITS:
        return _BASS_DIGITS[course]
    slashes = course - BASS_POSITION
    if slashes > _MAX_BASS_SLASHES:
        raise TabExportError("course", course)
    return "/" * slashes + _fret_text(fret, italian=False)


def _positions(notes: list[tuple[int, int]], *, italian: bool) -> list[str]:
    slots = [" "] * POSITIONS
    for course, fret in sorted(notes):
        if course <= TREBLE_POSITIONS:
            # Italian tablature puts the lowest course on the top line.
            index = TREBLE_POSITIONS - course if italian else course - 1
            slots[index] = _fret_text(fret, italian=italian)
        elif slots[BASS_POSITION - 1] == " ":
            slots[BASS_POSITION - 1] = _bass_text(course, fret)
        elif course <= POSITIONS and slots[course - 1] == " ":
            slots[course - 1] = _fret_text(fret, italian=False)
        else:
            raise TabExportError(_SECOND_BASS, course)
    return slots


def _chord_line(denom: int, dotted: bool, notes: list[tuple[int, int]], *, italian: bool) -> str:
    flag = _denom_to_flag(denom)
    dot = "." if dotted else ""
    if not notes:
        return f"R{flag}{dot}"
    text = "".join(_positions(notes, italian=italian)).rstrip()
    if not dotted and text[:1] in FLAG_MODIFIERS:
        text = _PLACE_MARKER + text
    return f"{flag}{dot}{text}"


def _chord_notes_for_column(
    context: _TabExportContext,
    bar_index: int,
    column: int,
) -> list[tuple[int, int]]:
    notes: list[tuple[int, int]] = []
    for string_index in range(context.piece.strings):
        key = (bar_index, string_index, column)
        fret = editor_fret_at(
            context.overrides,
            context.durations,
            bar_index=bar_index,
            string_index=string_index,
            column=column,
            style=context.style,
            french_c_shape=context.french_c,
        )
        if fret is None and context.style not in {"french", "italian"}:
            fret = _french_to_fret(context.overrides.get(key, ""))
        if fret is not None:
            notes.append((string_index + 1, fret))
    return notes


def _source_chords(context: _TabExportContext, bar: Bar) -> list[tuple[int, bool, list[tuple[int, int]]]]:
    chords: list[tuple[int, bool, list[tuple[int, int]]]] = []
    for chord in bar.chords:
        denom = note_type_to_denom(chord.note_type) or context.default_duration
        notes = [(note.string, note.fret) for note in chord.notes]
        chords.append((denom, bool(chord.dotted), notes))
    return chords


def _edited_chords(
    context: _TabExportContext,
    bar_index: int,
) -> list[tuple[int, bool, list[tuple[int, int]]]]:
    chords: list[tuple[int, bool, list[tuple[int, int]]]] = []
    for column in editor_event_columns(context.overrides, bar_index=bar_index):
        if column >= context.bar_width:
            continue
        notes = _chord_notes_for_column(context, bar_index, column)
        # A rest is a rhythm flag over an empty column.
        if notes or editor_rest_at(context.overrides, bar_index=bar_index, column=column):
            chords.append(
                (
                    _denom_for_column(context, bar_index, column),
                    (bar_index, column) in context.dotted,
                    notes,
                ),
            )
    return chords


def _bar_lines(context: _TabExportContext, bar_index: int, bar: Bar, meter_line: str | None) -> list[str]:
    lines = [meter_line] if meter_line else []
    chords = _source_chords(context, bar) if bar.chords else _edited_chords(context, bar_index)
    lines.extend(_chord_line(denom, dotted, notes, italian=context.italian) for denom, dotted, notes in chords)
    if not chords and not meter_line:
        # An empty measure needs a line of its own, or it disappears on read.
        lines.append(_time_signature_line(context.settings.get("time")) or "S")
    lines.append("b")
    return lines


def _meter_lines(context: _TabExportContext) -> list[str | None]:
    """An `S` line on the first bar, where the meter changes, and on empty bars (which need a line to exist)."""

    lines: list[str | None] = []
    previous: str | None = None
    for index, bar in enumerate(context.piece.bars):
        meter = bar.time_sig or previous or context.settings.get("time")
        needed = index == 0 or meter != previous or not bar.chords
        lines.append(_time_signature_line(meter) if needed else None)
        previous = meter
    return lines


def _system_breaks(piece: Piece) -> set[int]:
    """Bars after which a new system starts; the program never wraps lines by itself."""

    breaks = {index for index, bar in enumerate(piece.bars) if bar.system_break}
    if breaks:
        return breaks
    return set(range(_DEFAULT_BARS_PER_SYSTEM - 1, len(piece.bars), _DEFAULT_BARS_PER_SYSTEM))


def _setting_lines(context: _TabExportContext) -> list[str]:
    lines = [ITALIAN_SETTING] if context.italian else []
    tuning = context.piece.tuning or context.settings.get("tuning")
    if tuning:
        program = scientific_to_tuning(tuning)
        # Keep in a comment a tuning the program's notation cannot spell or that
        # would not read back as written (below A1, or not listed bass first).
        exact = program is not None and read_tuning(program) == tuning.lower()
        lines.append(f"-tuning {program}" if exact else f"% tuning: {tuning}")
    tempo = context.piece.tempo or context.settings.get("tempo")
    if tempo:
        lines.append(f"% tempo: {tempo}")
    return lines


def _header_lines(context: _TabExportContext) -> list[str]:
    lines = [HEADER, *_setting_lines(context)]
    title = context.piece.title or ""
    composer = context.piece.composer or ""
    if title and composer:
        lines.append(f"{{{title}/{composer}}}")
    elif title:
        lines.append(f"{{{title}}}")
    elif composer:
        lines.append(f"{{{composer}}}")
    if context.piece.author:
        lines.append(f"{{{context.piece.author}}}")
    lines.append("")
    return lines


def export_tab(
    piece: Piece,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    bar_width: int,
    *,
    settings: dict[str, str] | None = None,
    dotted: set[tuple[int, int]] | None = None,
    ornaments: dict[tuple[int, int], str] | None = None,
    annotations: dict[tuple[int, int], str] | None = None,
    slurs: list[tuple[int, int, int]] | None = None,
    ties: list[tuple[int, int, int]] | None = None,
    holds: list[tuple[int, int, int]] | None = None,
) -> str:
    _ = (ornaments, annotations, slurs, ties, holds)
    settings_map = settings or {}
    style = settings_map.get("style") or piece.style or "french"
    french_c = settings_map.get("frenchc") or "normal"
    context = _TabExportContext(
        piece,
        overrides,
        durations,
        bar_width,
        settings_map,
        dotted or set(),
        style,
        french_c,
    )
    lines = [*_header_lines(context), "b"]
    breaks = _system_breaks(piece)
    last = len(piece.bars) - 1
    for b_idx, (bar, meter_line) in enumerate(zip(piece.bars, _meter_lines(context), strict=True)):
        lines.extend(_bar_lines(context, b_idx, bar, meter_line))
        if b_idx in breaks and b_idx != last:
            lines.extend(["", "b"])
    lines.append("e")
    return "\n".join(lines) + "\n"


def export_ascii(
    piece: Piece,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    bar_width: int,
    *,
    settings: dict[str, str] | None = None,
    ornaments: dict[tuple[int, int], str] | None = None,
    annotations: dict[tuple[int, int], str] | None = None,
    slurs: list[tuple[int, int, int]] | None = None,
    ties: list[tuple[int, int, int]] | None = None,
    holds: list[tuple[int, int, int]] | None = None,
) -> str:
    _ = (ornaments, annotations, slurs, ties, holds)
    lines: list[str] = []
    default_duration = 4
    settings_map = settings or {}
    style = settings_map.get("style") or "french"
    french_c = settings_map.get("frenchc") or "normal"
    reverse_strings = style == "italian" and (settings_map.get("italianorient") or "normal") == "reverse"
    for b_idx, bar in enumerate(piece.bars):
        cells = (
            bar_cells_from_chords(
                bar,
                piece.strings,
                bar_width,
                default_duration,
                style,
                french_c=french_c,
            )
            if bar.chords
            else bar_cells(
                bar,
                piece.strings,
                bar_width,
                style,
                french_c=french_c,
            )
        )
        for s_idx in range(piece.strings):
            actual = piece.strings - 1 - s_idx if reverse_strings else s_idx
            for col in range(bar_width):
                key = (b_idx, actual, col)
                if key in overrides:
                    cells[actual][col] = overrides[key]
        if bar.chords:
            positions = chord_positions(bar, bar_width, default_duration)
            flag_cells = flag_row(positions, bar_width)
            lines.append("".join(flag_cells))
        else:
            flag_positions = flag_positions_from_durations(
                durations,
                b_idx,
                piece.strings,
                bar_width,
                default_duration,
                dotted=None,
            )
            flag_cells = flag_row(flag_positions, bar_width)
            lines.append("".join(flag_cells))
        for s_idx in range(piece.strings):
            actual = piece.strings - 1 - s_idx if reverse_strings else s_idx
            row = "".join(cells[actual])
            label = f"{piece.strings - actual:>2}|"
            lines.append(label + row)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def export_tab_to_file(
    path: str,
    piece: Piece,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    bar_width: int,
    *,
    settings: dict[str, str] | None = None,
    dotted: set[tuple[int, int]] | None = None,
    ornaments: dict[tuple[int, int], str] | None = None,
    annotations: dict[tuple[int, int], str] | None = None,
    slurs: list[tuple[int, int, int]] | None = None,
    ties: list[tuple[int, int, int]] | None = None,
    holds: list[tuple[int, int, int]] | None = None,
) -> None:
    content = export_tab(
        piece,
        overrides,
        durations,
        bar_width,
        settings=settings,
        dotted=dotted,
        ornaments=ornaments,
        annotations=annotations,
        slurs=slurs,
        ties=ties,
        holds=holds,
    )
    with Path(path).open("w", encoding="utf-8") as f:
        f.write(content)


__all__ = ["TabExportError", "export_ascii", "export_tab", "export_tab_to_file"]
