from __future__ import annotations

from pathlib import Path

from petrucci.model import Piece
from petrucci.render_utils import (
    bar_cells,
    bar_cells_from_chords,
    chord_positions,
    flag_positions_from_durations,
    flag_row,
    format_fret,
    note_type_to_denom,
)
from petrucci.tab_input import editor_event_columns, editor_fret_at


class TabExportError(ValueError):
    """Raised when the legacy TAB format cannot preserve an edit."""

    def __init__(self, fret: int) -> None:
        super().__init__(f"TAB cannot preserve Italian fret {fret}; export LilyPond, MIDI, or MusicXML")


def export_tab(  # noqa: PLR0912, C901
    piece: Piece,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    bar_width: int,
    settings: dict[str, str] | None = None,
    dotted: set[tuple[int, int]] | None = None,
    ornaments: dict[tuple[int, int], str] | None = None,
    annotations: dict[tuple[int, int], str] | None = None,
    slurs: list[tuple[int, int, int]] | None = None,
    ties: list[tuple[int, int, int]] | None = None,
    holds: list[tuple[int, int, int]] | None = None,
) -> str:
    _ = (ornaments, annotations, slurs, ties, holds)
    settings_map = settings or {}
    style = settings_map.get("style") or piece.style or "french"
    french_c = settings_map.get("frenchc") or "normal"
    default_duration = 4

    def time_signature_line(value: str | None) -> str | None:
        if not value:
            return None
        text = value.strip()
        if text == "C":
            return "Sc"
        if text == "C|":
            return "Sc|"
        return f"S{text}"

    def french_to_fret(ch: str) -> int | None:
        if ch == "r":
            return 2
        if "a" <= ch <= "p":
            return ord(ch) - ord("a")
        return None

    def denom_for_column(bar_index: int, col: int) -> int:
        found = None
        for s_idx in range(piece.strings):
            key = (bar_index, s_idx, col)
            if key in durations:
                denom = durations[key]
                if found is None or denom > found:
                    found = denom
        return found if found is not None else default_duration

    def denom_to_flag(denom: int) -> str:
        return {
            1: "W",
            2: "w",
            4: "0",
            8: "1",
            16: "2",
            32: "3",
            64: "4",
            128: "5",
        }.get(denom, "0")

    def format_fret_char(fret: int) -> str:
        if style == "italian" and fret > 10:
            raise TabExportError(fret)
        if style == "italian" and fret == 10:
            return "x"
        text = format_fret(style, fret, french_c=french_c)
        return text[0] if text else "-"

    def chord_notes_for_col(bar_index: int, col: int) -> list[tuple[int, int]]:
        notes: list[tuple[int, int]] = []
        for s_idx in range(piece.strings):
            key = (bar_index, s_idx, col)
            fret = editor_fret_at(
                overrides,
                durations,
                bar_index=bar_index,
                string_index=s_idx,
                column=col,
                style=style,
                french_c_shape=french_c,
            )
            if fret is None and style not in {"french", "italian"}:
                fret = french_to_fret(overrides.get(key, ""))
            if fret is None:
                continue
            notes.append((s_idx + 1, fret))
        return notes

    lines: list[str] = []
    lines.append("% Generated by oud")
    lines.append("-C")
    tuning = piece.tuning or settings_map.get("tuning")
    if tuning:
        lines.append(f"-tuning {tuning}")
    title = piece.title or ""
    composer = piece.composer or ""
    if title and composer:
        lines.append(f"{{{title}/{composer}}}")
    elif title:
        lines.append(f"{{{title}}}")
    elif composer:
        lines.append(f"{{{composer}}}")
    if piece.author:
        lines.append(f"{{{piece.author}}}")
    lines.append("")

    for b_idx, bar in enumerate(piece.bars):
        lines.append("b")
        sig_line = time_signature_line(bar.time_sig or settings_map.get("time"))
        if sig_line:
            lines.append(sig_line)
        chords: list[tuple[int, bool, list[tuple[int, int]]]] = []
        if bar.chords:
            for chord in bar.chords:
                denom = note_type_to_denom(chord.note_type) or default_duration
                notes = [(note.string, note.fret) for note in chord.notes]
                chords.append((denom, bool(chord.dotted), notes))
        else:
            for col in editor_event_columns(overrides, bar_index=b_idx):
                if col >= bar_width:
                    continue
                notes = chord_notes_for_col(b_idx, col)
                if not notes:
                    continue
                denom = denom_for_column(b_idx, col)
                dot = (b_idx, col) in (dotted or set())
                chords.append((denom, dot, notes))
        for denom, dot, notes in chords:
            flag = denom_to_flag(denom)
            row = ["-" for _ in range(piece.strings)]
            for string, fret in notes:
                if not (1 <= string <= piece.strings):
                    continue
                idx = string - 1
                row[idx] = format_fret_char(fret)
            line = flag + ("." if dot else "") + "".join(row)
            lines.append(line)
        lines.append("")
    lines.append("e")
    return "\n".join(lines) + "\n"


def export_ascii(
    piece: Piece,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    bar_width: int,
    settings: dict[str, str] | None = None,
    ornaments: dict[tuple[int, int], str] | None = None,
    annotations: dict[tuple[int, int], str] | None = None,
    slurs: list[tuple[int, int, int]] | None = None,
    ties: list[tuple[int, int, int]] | None = None,
    holds: list[tuple[int, int, int]] | None = None,
) -> str:
    _ = (ornaments, annotations, slurs, ties, holds)
    lines: list[str] = []
    default_duration = 4
    settings_map = settings or {}
    style = settings_map.get("style") or "french"
    french_c = settings_map.get("frenchc") or "normal"
    reverse_strings = style == "italian" and (settings_map.get("italianorient") or "normal") == "reverse"
    for b_idx, bar in enumerate(piece.bars):
        cells = (
            bar_cells_from_chords(
                bar,
                piece.strings,
                bar_width,
                default_duration,
                style,
                french_c=french_c,
            )
            if bar.chords
            else bar_cells(
                bar,
                piece.strings,
                bar_width,
                style,
                french_c=french_c,
            )
        )
        for s_idx in range(piece.strings):
            actual = piece.strings - 1 - s_idx if reverse_strings else s_idx
            for col in range(bar_width):
                key = (b_idx, actual, col)
                if key in overrides:
                    cells[actual][col] = overrides[key]
        if bar.chords:
            positions = chord_positions(bar, bar_width, default_duration)
            flag_cells = flag_row(positions, bar_width)
            lines.append("".join(flag_cells))
        else:
            flag_positions = flag_positions_from_durations(
                durations,
                b_idx,
                piece.strings,
                bar_width,
                default_duration,
            )
            flag_cells = flag_row(flag_positions, bar_width)
            lines.append("".join(flag_cells))
        for s_idx in range(piece.strings):
            actual = piece.strings - 1 - s_idx if reverse_strings else s_idx
            row = "".join(cells[actual])
            label = f"{piece.strings - actual:>2}|"
            lines.append(label + row)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def export_tab_to_file(
    path: str,
    piece: Piece,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    bar_width: int,
    settings: dict[str, str] | None = None,
    dotted: set[tuple[int, int]] | None = None,
    ornaments: dict[tuple[int, int], str] | None = None,
    annotations: dict[tuple[int, int], str] | None = None,
    slurs: list[tuple[int, int, int]] | None = None,
    ties: list[tuple[int, int, int]] | None = None,
    holds: list[tuple[int, int, int]] | None = None,
) -> None:
    content = export_tab(
        piece,
        overrides,
        durations,
        bar_width,
        settings=settings,
        dotted=dotted,
        ornaments=ornaments,
        annotations=annotations,
        slurs=slurs,
        ties=ties,
        holds=holds,
    )
    with Path(path).open("w", encoding="utf-8") as f:
        f.write(content)


__all__ = ["TabExportError", "export_ascii", "export_tab", "export_tab_to_file"]
