"""Reuse of a `.tab` file's own text when Oud writes it back (TODO C15).

A line is reused only while it still reads as the modelled content it came
from; anything edited is regenerated by `oud.exports.export_tab`.
"""

from __future__ import annotations

from oud.importers.tab import decode_chord_line, header_facts, unmodelled_header_lines
from oud.importers.tab_syntax import MILAN_OPTION, TabSyntax, read_time_signature
from petrucci.core.model import Bar, Chord, Piece


def verbatim_header(piece: Piece) -> list[str] | None:
    """The source header when it still gives the piece's title, composer, author, tuning and tempo."""

    header = piece.source_header
    # Oud writes Italian in the program's default order, so `-milan` cannot be kept.
    if not header or any(line.startswith("-") and MILAN_OPTION in line.split() for line in header):
        return None
    facts = (piece.title, piece.composer, piece.author, piece.tuning, piece.tempo)
    if header_facts(header) != facts:
        return None
    return header if header[-1].strip() == "" else [*header, ""]


def carried_header(piece: Piece) -> list[str]:
    return unmodelled_header_lines(piece.source_header)


def source_meter(bar: Bar) -> str | None:
    """The bar's own meter line while it still reads as the bar's meter."""

    source = bar.source
    if source is None or source.meter is None:
        return None
    return source.meter if read_time_signature(source.meter, TabSyntax()) == bar.time_sig else None


def reused_chord_line(chord: Chord, previous_note_type: int | None, *, italian: bool) -> str | None:
    if chord.source_text is None:
        return None
    decoded = decode_chord_line(chord.source_text, TabSyntax(italian=italian), previous_note_type)
    if decoded is None or (decoded.note_type, decoded.dotted) != (chord.note_type, chord.dotted):
        return None
    if _notes(decoded) != _notes(chord):
        return None
    return chord.source_text


def _notes(chord: Chord) -> list[tuple[int, int]]:
    return sorted((note.string, note.fret) for note in chord.notes)


def carried_lines(bar: Bar, position: int) -> list[str]:
    """Lines kept before event ``position``; ``len(bar.chords)`` is before the closing barline."""

    source = bar.source
    return [line for index, line in source.lines if index == position] if source is not None else []


def lines_after_barline(bar: Bar) -> list[str]:
    """Lines kept past the last event slot; they follow the closing barline."""

    source = bar.source
    return [line for index, line in source.lines if index > len(bar.chords)] if source is not None else []


def source_barline(bar: Bar) -> str:
    return bar.source.barline if bar.source is not None and bar.source.barline else "b"
