from __future__ import annotations

from petrucci.core.music.tuning import parse_tuning_pitches
from petrucci.input.tablature.style import resolve_tab_style_policy
from petrucci.rendering.staff.playback import PlaybackOverlayCache
from petrucci.rendering.system.loop import render_system_sequence
from petrucci.rendering.system.types import SystemRenderContext
from petrucci.terminal.canvas.screen import Screen


def render_systems(
    stdscr: Screen,
    *,
    piece,
    width: int,
    header_row: int,
    left_margin: int,
    systems: int,
    total_strings: int,
    display_indices: list[int],
    display_strings: int,
    bar_offset: int,
    cursor_bar: int,
    cursor_string: int,
    cursor_col: int,
    cursor_event: int | None = None,
    bar_width: int,
    overrides: dict[tuple[int, int, int], str],
    durations: dict[tuple[int, int, int], int],
    ornaments: dict[tuple[int, int], str],
    annotations: dict[tuple[int, int], str],
    highlights: set[tuple[int, int, int]],
    dotted: set[tuple[int, int]],
    slurs: list[tuple[int, int, int]],
    ties: list[tuple[int, int, int]],
    holds: list[tuple[int, int, int]],
    glisses: list[tuple[int, int, int]] | None,
    settings: dict[str, str],
    stave_breaks: set[int],
    playback_bar: int | None,
    playback_col: int | None,
    playback_markers: list[tuple[int, int]] | None,
    include_meta: bool,
    show_dur: bool,
    show_extras: bool,
    show_tuplets: bool,
    show_tactus: bool,
    hide_redundant: bool,
    double_stems: bool,
    reverse_strings: bool,
    max_chords: int,
    spacing_mode: str,
    spacing_fill: str,
    bar_gap: int,
    barpad: int,
    usable_width: int,
    bars_per_line_limit: int,
    default_duration: int,
    tuning_labels: list[str],
    basslabels: str,
    chord_wrap_limit: int,
    show_melody: bool = False,
    melody_rows_count: int = 1,
    show_lyrics: bool = False,
    lyric_rows_count: int = 0,
    vocal_pos: str = "bottom",
    playback_cache: PlaybackOverlayCache | None = None,
    cursor_display_maps: dict[int, list[int]] | None = None,
) -> None:
    context = SystemRenderContext(
        stdscr=stdscr,
        piece=piece,
        width=width,
        header_row=header_row,
        left_margin=left_margin,
        systems=systems,
        total_strings=total_strings,
        display_indices=display_indices,
        display_strings=display_strings,
        bar_offset=bar_offset,
        cursor_bar=cursor_bar,
        cursor_string=cursor_string,
        cursor_col=cursor_col,
        cursor_event=cursor_event,
        bar_width=bar_width,
        overrides=overrides,
        durations=durations,
        ornaments=ornaments,
        annotations=annotations,
        highlights=highlights,
        dotted=dotted,
        slurs=slurs,
        ties=ties,
        holds=holds,
        glisses=glisses or [],
        settings=settings,
        stave_breaks=stave_breaks,
        effective_playback_markers=_playback_markers(playback_markers, playback_bar, playback_col),
        include_meta=include_meta,
        show_dur=show_dur,
        show_extras=show_extras,
        show_tuplets=show_tuplets,
        show_tactus=show_tactus,
        hide_redundant=hide_redundant,
        double_stems=double_stems,
        reverse_strings=reverse_strings,
        max_chords=max_chords,
        spacing_mode=spacing_mode,
        spacing_fill=spacing_fill,
        bar_gap=bar_gap,
        barpad=barpad,
        usable_width=usable_width,
        bars_per_line_limit=bars_per_line_limit,
        default_duration=default_duration,
        tuning_labels=tuning_labels,
        basslabels=basslabels,
        chord_wrap_limit=chord_wrap_limit,
        show_melody=show_melody,
        melody_rows_count=max(1, melody_rows_count) if show_melody else 0,
        show_lyrics=show_lyrics,
        lyric_rows_count=lyric_rows_count,
        vocal_pos=vocal_pos,
        playback_cache=playback_cache,
        cursor_display_maps=cursor_display_maps,
        style_policy=resolve_tab_style_policy(settings),
        tuning_pitches=parse_tuning_pitches(settings.get("tuning", "")),
        duet_width_lock=settings.get("duetwidthlock", "off") == "on",
    )
    render_system_sequence(context)


def _playback_markers(
    markers: list[tuple[int, int]] | None,
    playback_bar: int | None,
    playback_col: int | None,
) -> list[tuple[int, int]]:
    resolved = list(markers or [])
    if not resolved and playback_bar is not None and playback_col is not None:
        resolved.append((playback_bar, playback_col))
    return resolved
