import random
import string

import pytest

from oud.importers.tab import (
    load_tab,
    load_tab_data,
    parse_tab_text_data,
    reparse_tab_text_auto_delta,
    reparse_tab_text_delta,
)


def _piece_signature(piece) -> tuple:
    return (
        piece.title,
        piece.author,
        piece.composer,
        piece.style,
        tuple(
            (
                bar.time_sig,
                tuple(
                    (
                        chord.note_type,
                        chord.dotted,
                        chord.grid,
                        tuple((note.string, note.fret) for note in chord.notes),
                    )
                    for chord in bar.chords
                ),
            )
            for bar in piece.bars
        ),
    )


def test_load_tab_simple(tmp_path) -> None:
    content = "{Title}\n{Author}\n\nb\n0ca\n1 d \nb\n"
    path = tmp_path / "simple.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.title == "Title"
    assert piece.author == "Author"
    assert len(piece.bars) == 1
    assert len(piece.bars[0].chords) == 2


def test_load_tab_partial_file_recovers_bars_and_warns(tmp_path) -> None:
    path = tmp_path / "partial.tab"
    path.write_text("{Partial}\nb\n0a-----\n", encoding="utf-8")

    parsed = load_tab_data(str(path))

    assert parsed is not None
    assert len(parsed.piece.bars) == 1
    assert "missing final 'e'" in parsed.piece.import_warnings[0]


def test_load_tab_empty_file_returns_named_warning_piece(tmp_path) -> None:
    path = tmp_path / "broken.tab"
    path.write_text("this is not tablature\n", encoding="utf-8")

    piece = load_tab(str(path))

    assert piece.title == "broken"
    assert piece.bars == []
    assert "no recoverable bars" in piece.import_warnings[0]


def test_load_tab_data_cripps_format(tmp_path) -> None:
    content = "\n".join(
        [
            "% Generated by oud",
            "-C",
            "-tuning g2c3f3a3d4g4",
            "{Title/Composer}",
            "{Author}",
            "",
            "b",
            "Sc",
            "0a-----",
            "",
            "e",
        ],
    )
    path = tmp_path / "export.tab"
    path.write_text(content, encoding="utf-8")
    parsed = load_tab_data(str(path))
    assert parsed is not None
    assert parsed.piece.title == "Title"
    assert parsed.piece.composer == "Composer"
    assert parsed.piece.author == "Author"
    assert parsed.piece.tuning == "g2c3f3a3d4g4"
    assert parsed.piece.bars


def test_parse_french_extended_letters(tmp_path) -> None:
    content = "\n".join(
        [
            "{Test}",
            "b",
            "0qrst--",
            "e",
        ],
    )
    path = tmp_path / "extended.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.bars
    notes = piece.bars[0].chords[0].notes
    assert [note.fret for note in notes[:4]] == [15, 16, 17, 18]


def test_load_tab_hash_flag_lines_are_parsed_as_chords(tmp_path) -> None:
    content = "\n".join(
        [
            "{HashFlags}",
            "b",
            "#2 cd",
            "x e",
            "b",
            "e",
        ],
    )
    path = tmp_path / "hash_flags.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.bars
    assert len(piece.bars[0].chords) == 2
    assert piece.bars[0].chords[0].note_type == 6
    assert piece.bars[0].chords[1].note_type == 6


def test_load_tab_multisection_continues_after_e_marker(tmp_path) -> None:
    content = "\n".join(
        [
            "{Multi}",
            "b",
            "0a",
            "e",
            "{Second}",
            "b",
            "1b",
            "e",
        ],
    )
    path = tmp_path / "multi_section.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert len(piece.bars) == 2
    assert len(piece.bars[0].chords) == 1
    assert len(piece.bars[1].chords) == 1


def test_load_tab_without_header_body_separator(tmp_path) -> None:
    content = "\n".join(
        [
            "{NoSeparator/Composer}",
            "b",
            "0a",
            "1b",
            "e",
        ],
    )
    path = tmp_path / "no_sep.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.title == "NoSeparator"
    assert piece.composer == "Composer"
    assert piece.bars
    assert len(piece.bars[0].chords) == 2


def test_load_tab_malformed_fuzz_smoke_does_not_crash(tmp_path) -> None:
    rnd = random.Random(1337)  # noqa: S311 - deterministic parser fuzz smoke seed
    alphabet = string.ascii_letters + string.digits + "{}[]#:/|-% \t"
    for idx in range(40):
        lines = ["{Fuzz}"]
        for _ in range(rnd.randint(1, 12)):
            line_len = rnd.randint(0, 18)
            lines.append("".join(rnd.choice(alphabet) for _ in range(line_len)))
        path = tmp_path / f"fuzz_{idx}.tab"
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        # Parser should degrade gracefully on malformed input and never crash.
        piece = load_tab(str(path))
        assert piece is not None


@pytest.mark.parametrize(
    "body_lines",
    [
        # malformed hash flag/rhythm tokens
        ["b", "#x ???", "#999", "e"],
        # broken rhythm prefixes + junk spacing
        ["b", "S", "  ", "\t\t", "x  --", "e"],
        # repeated section/bar markers and stray comment-ish syntax
        ["b", "%bad", "b", "e", "e", "b", "0a", "e"],
        # mixed malformed whitespace around plausible content
        ["b", "   0a   ", "", " \t1b\t ", "   ", "e"],
        # impossible duration-like noise around note rows
        ["b", "##2", "###", "r??", "0----", "e"],
    ],
)
def test_load_tab_malformed_flags_rhythms_whitespace_cases_do_not_crash(tmp_path, body_lines) -> None:
    path = tmp_path / "malformed_cases.tab"
    path.write_text("{Malformed}\n" + "\n".join(body_lines) + "\n", encoding="utf-8")
    piece = load_tab(str(path))
    assert piece is not None


def test_load_tab_whitespace_comment_option_noise_preserves_parse_signature(tmp_path) -> None:
    canonical_lines = [
        "{Norm/Composer}",
        "#time: Sc",
        "b",
        "0a   ",
        "1 b  ",
        "x c  ",
        "e",
    ]
    noisy_lines = [
        "{Norm/Composer}",
        "",
        "-C",
        "#time: Sc",
        "% ignored comment",
        "b",
        "0a   ",
        "",
        "1 b  ",
        "  ",  # blank-ish line
        "% another comment",
        "x c  ",
        "\t",
        "e",
        "",
    ]
    canonical = tmp_path / "canonical.tab"
    noisy = tmp_path / "noisy.tab"
    canonical.write_text("\n".join(canonical_lines) + "\n", encoding="utf-8")
    noisy.write_text("\n".join(noisy_lines) + "\n", encoding="utf-8")
    assert _piece_signature(load_tab(str(noisy))) == _piece_signature(load_tab(str(canonical)))


def test_load_tab_rhythm_alias_x_matches_explicit_repeat_flag(tmp_path) -> None:
    alias = tmp_path / "alias.tab"
    explicit = tmp_path / "explicit.tab"
    alias.write_text(
        "\n".join(
            [
                "{Alias}",
                "b",
                "1a",
                "x b",
                "x  c",
                "e",
            ],
        )
        + "\n",
        encoding="utf-8",
    )
    explicit.write_text(
        "\n".join(
            [
                "{Alias}",
                "b",
                "1a",
                "1 b",
                "1  c",
                "e",
            ],
        )
        + "\n",
        encoding="utf-8",
    )
    assert _piece_signature(load_tab(str(alias))) == _piece_signature(load_tab(str(explicit)))


def test_load_tab_y_prefix_normalization_preserves_semantics(tmp_path) -> None:
    prefixed = tmp_path / "prefixed.tab"
    normalized = tmp_path / "normalized.tab"
    prefixed.write_text(
        "\n".join(
            [
                "{YPrefix}",
                "b",
                "ya",
                "Y1b",
                "Y2c",
                "e",
            ],
        )
        + "\n",
        encoding="utf-8",
    )
    normalized.write_text(
        "\n".join(
            [
                "{YPrefix}",
                "b",
                "0a",
                "1b",
                "2c",
                "e",
            ],
        )
        + "\n",
        encoding="utf-8",
    )
    assert _piece_signature(load_tab(str(prefixed))) == _piece_signature(load_tab(str(normalized)))


def test_parse_tab_text_data_matches_file_loader_signature(tmp_path) -> None:
    content = (
        "\n".join(
            [
                "{Inline/Composer}",
                "#time: Sc",
                "b",
                "0a",
                "1 b",
                "e",
            ],
        )
        + "\n"
    )
    path = tmp_path / "inline.tab"
    path.write_text(content, encoding="utf-8")
    parsed_inline = parse_tab_text_data(content)
    parsed_file = load_tab_data(str(path))
    assert parsed_inline is not None
    assert parsed_file is not None
    assert _piece_signature(parsed_inline.piece) == _piece_signature(parsed_file.piece)


def test_parse_tab_text_data_reports_stable_bar_line_spans() -> None:
    content = "\n".join(
        [
            "{Span}",
            "#time: Sc",
            "b",
            "0a",
            "1 b",
            "e",
            "{Second}",
            "b",
            "Sc|",
            "0c",
            "e",
        ],
    )
    parsed = parse_tab_text_data(content)
    assert parsed is not None
    assert len(parsed.piece.bars) == 2
    # First bar spans the two chord rows; second includes explicit in-bar timesig row and chord row.
    assert parsed.bar_line_spans == [(3, 4), (8, 9)]


def test_reparse_tab_text_delta_reports_affected_bar_ranges_for_body_change() -> None:
    base = "\n".join(
        [
            "{Span}",
            "#time: Sc",
            "b",
            "0a",
            "1 b",
            "e",
            "b",
            "0c",
            "e",
        ],
    )
    prev = parse_tab_text_data(base)
    assert prev is not None
    changed = base.replace("1 b", "1 c")
    delta = reparse_tab_text_delta(
        prev,
        changed,
        changed_line_start=4,
        changed_line_end=4,
    )
    assert delta.data is not None
    assert delta.old_bar_range == (0, 1)
    assert delta.new_bar_range == (0, 1)
    assert delta.full_reparse is False
    assert delta.reason is None
    assert delta.data.piece.bars[0].chords[1].notes[0].fret == 2


def test_reparse_tab_text_delta_falls_back_on_structural_line_change() -> None:
    base = "\n".join(
        [
            "{Span}",
            "#time: Sc",
            "b",
            "0a",
            "1 b",
            "e",
            "b",
            "0c",
            "e",
        ],
    )
    prev = parse_tab_text_data(base)
    assert prev is not None
    changed = base.replace("1 b", "b")
    delta = reparse_tab_text_delta(
        prev,
        changed,
        changed_line_start=4,
        changed_line_end=4,
    )
    assert delta.data is not None
    assert delta.full_reparse is True
    assert delta.reason == "structural_change"


def test_reparse_tab_text_delta_marks_header_change_as_full_reparse_reason() -> None:
    base = "\n".join(
        [
            "{Title}",
            "#time: Sc",
            "b",
            "0a",
            "e",
        ],
    )
    prev = parse_tab_text_data(base)
    assert prev is not None
    changed = base.replace("{Title}", "{NewTitle}")
    delta = reparse_tab_text_delta(
        prev,
        changed,
        changed_line_start=0,
        changed_line_end=0,
    )
    assert delta.data is not None
    assert delta.full_reparse is True
    assert delta.reason == "header_or_metadata_change"


def test_reparse_tab_text_auto_delta_detects_inserted_body_line_and_reports_bar_ranges() -> None:
    base = "\n".join(
        [
            "{AutoDelta}",
            "#time: Sc",
            "b",
            "0a",
            "1 b",
            "e",
            "b",
            "0c",
            "e",
        ],
    )
    prev = parse_tab_text_data(base)
    assert prev is not None
    changed = "\n".join(
        [
            "{AutoDelta}",
            "#time: Sc",
            "b",
            "0a",
            "1 b",
            "x  c",
            "e",
            "b",
            "0c",
            "e",
        ],
    )
    delta = reparse_tab_text_auto_delta(prev, changed)
    assert delta.data is not None
    assert delta.old_bar_range in {(0, 0), (0, 1)}
    assert delta.new_bar_range == (0, 1)
    assert delta.full_reparse is True
    assert delta.reason == "line_count_changed"


def test_reparse_tab_text_auto_delta_returns_no_change_delta_for_identical_text() -> None:
    base = "\n".join(
        [
            "{NoChange}",
            "b",
            "0a",
            "e",
        ],
    )
    prev = parse_tab_text_data(base)
    assert prev is not None
    delta = reparse_tab_text_auto_delta(prev, base)
    assert delta.data is not None
    assert delta.full_reparse is False
    assert delta.reason == "no_change"
    assert delta.old_bar_range == (0, 0)
    assert delta.new_bar_range == (0, 0)
