from oud.core.tab_parser import load_tab, load_tab_data


def test_load_tab_simple(tmp_path) -> None:
    content = "{Title}\n{Author}\n\nb\n0ca\n1 d \nb\n"
    path = tmp_path / "simple.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.title == "Title"
    assert piece.author == "Author"
    assert len(piece.bars) == 1
    assert len(piece.bars[0].chords) == 2


def test_load_tab_data_cripps_format(tmp_path) -> None:
    content = "\n".join(
        [
            "% Generated by oud",
            "-C",
            "-tuning g2c3f3a3d4g4",
            "{Title/Composer}",
            "{Author}",
            "",
            "b",
            "Sc",
            "0a-----",
            "",
            "e",
        ],
    )
    path = tmp_path / "export.tab"
    path.write_text(content, encoding="utf-8")
    parsed = load_tab_data(str(path))
    assert parsed is not None
    assert parsed.piece.title == "Title"
    assert parsed.piece.composer == "Composer"
    assert parsed.piece.author == "Author"
    assert parsed.piece.tuning == "g2c3f3a3d4g4"
    assert parsed.piece.bars


def test_parse_french_extended_letters(tmp_path) -> None:
    content = "\n".join(
        [
            "{Test}",
            "b",
            "0qrst--",
            "e",
        ],
    )
    path = tmp_path / "extended.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.bars
    notes = piece.bars[0].chords[0].notes
    assert [note.fret for note in notes[:4]] == [15, 16, 17, 18]


def test_load_tab_hash_flag_lines_are_parsed_as_chords(tmp_path) -> None:
    content = "\n".join(
        [
            "{HashFlags}",
            "b",
            "#2 cd",
            "x e",
            "b",
            "e",
        ],
    )
    path = tmp_path / "hash_flags.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.bars
    assert len(piece.bars[0].chords) == 2
    assert piece.bars[0].chords[0].note_type == 6
    assert piece.bars[0].chords[1].note_type == 6


def test_load_tab_multisection_continues_after_e_marker(tmp_path) -> None:
    content = "\n".join(
        [
            "{Multi}",
            "b",
            "0a",
            "e",
            "{Second}",
            "b",
            "1b",
            "e",
        ],
    )
    path = tmp_path / "multi_section.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert len(piece.bars) == 2
    assert len(piece.bars[0].chords) == 1
    assert len(piece.bars[1].chords) == 1


def test_load_tab_without_header_body_separator(tmp_path) -> None:
    content = "\n".join(
        [
            "{NoSeparator/Composer}",
            "b",
            "0a",
            "1b",
            "e",
        ],
    )
    path = tmp_path / "no_sep.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.title == "NoSeparator"
    assert piece.composer == "Composer"
    assert piece.bars
    assert len(piece.bars[0].chords) == 2
