"""Reading files of the original `tab` program; see docs/tab-format.md."""

from __future__ import annotations

from pathlib import Path

from oud.editor.services.bootstrap import init_state
from oud.editor.services.io.files import cmd_write
from oud.importers.tab import parse_tab_text_data
from petrucci.core.model import Piece
from petrucci.core.music.tuning import tuning_preset

OUD_HEADER = "% Generated by oud\n"


def _piece(body: str) -> Piece:
    data = parse_tab_text_data(f"b\n{body}b\ne\n")
    assert data is not None
    return data.piece


def _chords(body: str) -> list[list[tuple[int, int]]]:
    return [[(note.string, note.fret) for note in chord.notes] for chord in _piece(body).bars[0].chords]


def test_bass_courses_share_position_seven() -> None:
    body = "2a     a\n2a     /a\n2a     //a\n2a     ///a\n2a     4\n2       b\n"
    assert _chords(body) == [
        [(1, 0), (7, 0)],
        [(1, 0), (8, 0)],
        [(1, 0), (9, 0)],
        [(1, 0), (10, 0)],
        [(1, 0), (11, 0)],
        [(8, 1)],
    ]
    assert _piece(body).strings == 11


def test_opening_a_ten_course_file_keeps_its_bass_notes(tmp_path: Path) -> None:
    path = tmp_path / "bass.tab"
    path.write_text("-tuning C4D4E4F4G4c3f3a2d2g2\nb\n2a     /a\n2b     a\nb\ne\n", encoding="utf-8")

    state = init_state(str(path), config_path=str(tmp_path / "config.toml"))

    notes = [[(note.string, note.fret) for note in chord.notes] for chord in state.piece.bars[0].chords]
    assert notes == [[(1, 0), (8, 0)], [(1, 1), (7, 0)]]
    assert state.piece.strings == 10


def test_rest_lines_keep_their_time() -> None:
    chords = _piece("R2\nR1.\n2a\n").bars[0].chords
    assert [(chord.note_type, chord.dotted, chord.notes) for chord in chords[:2]] == [(6, False, []), (5, True, [])]


def test_fret_letters_follow_the_program() -> None:
    assert _chords("2j\n2k\n2l\n2p\n") == [[(1, 9)], [(1, 9)], [(1, 10)], [(1, 14)]]


def test_triplet_lines_are_kept_and_reported() -> None:
    piece = _piece("t3a\nxb\nxc\n")
    assert [[(n.string, n.fret) for n in chord.notes] for chord in piece.bars[0].chords] == [
        [(1, 0)],
        [(1, 1)],
        [(1, 2)],
    ]
    assert piece.bars[0].chords[0].note_type == 7
    assert any("triplet" in warning for warning in piece.import_warnings)


def test_prefix_and_postfix_symbols_take_no_position() -> None:
    assert _chords('2+a\n2+*ab\n2xa\n2\\1a\n2a&+c\n2"-c\n') == [
        [(1, 0)],
        [(1, 0), (2, 1)],
        [(1, 0)],
        [(1, 0)],
        [(1, 0), (2, 2)],
        [(1, 2)],
    ]


def test_marks_that_take_a_position_do_not_become_notes() -> None:
    assert _chords("2[a\n2]b\n2U\n2a.\n2a|b\n") == [[(2, 0)], [(2, 1)], [], [(1, 0)], [(1, 0), (3, 1)]]


def test_modifier_after_the_flag_is_not_course_one() -> None:
    chords = _piece("2-a\n2.b\n#2c\n2!d\n").bars[0].chords
    assert [[(n.string, n.fret) for n in chord.notes] for chord in chords] == [[(1, 0)], [(1, 1)], [(1, 2)], [(1, 3)]]
    assert [chord.dotted for chord in chords] == [False, True, False, False]


def test_high_frets_and_escapes() -> None:
    assert _chords("2a\n2N12\n2 N10\n") == [[(1, 0)], [(1, 12)], [(2, 10)]]


def test_italian_digits_count_from_the_lowest_course_unless_milan() -> None:
    # `!` straight after the flag hides the flag, so the escaped tenth fret needs the `-` place marker.
    assert _chords("21 3\n2-!x\n2z\n") == [[(4, 3), (6, 1)], [(6, 10)], [(6, 0)]]

    data = parse_tab_text_data("-milan\nb\n21 3\nb\ne\n")
    assert data is not None
    assert [[(n.string, n.fret) for n in chord.notes] for chord in data.piece.bars[0].chords] == [[(1, 1), (3, 3)]]


def test_barline_lines() -> None:
    piece = _piece("2a\nB\n2b\n.bb.\n2c\nB!\n2d\nBa\n")
    assert [[(n.string, n.fret) for c in bar.chords for n in c.notes] for bar in piece.bars] == [
        [(1, 0)],
        [(1, 1)],
        [(1, 2)],
        [(1, 3), (1, 0)],
    ]
    assert piece.bars[3].chords[1].note_type == 2


def test_oud_written_files_keep_their_legacy_meaning() -> None:
    data = parse_tab_text_data(f"{OUD_HEADER}-tuning g2c3f3a3d4g4\nb\n2-a----\n0a-----\nb\ne\n")
    assert data is not None
    assert [[(n.string, n.fret) for n in chord.notes] for chord in data.piece.bars[0].chords] == [[(2, 0)], [(1, 0)]]
    assert data.piece.tuning == "g2c3f3a3d4g4"

    italian = parse_tab_text_data(f"{OUD_HEADER}b\n2x3----\nb\ne\n")
    assert italian is not None
    assert [(n.string, n.fret) for n in italian.piece.bars[0].chords[0].notes] == [(1, 10), (2, 3)]


def test_program_tuning_is_read_as_scientific_pitch() -> None:
    data = parse_tab_text_data("-tuning C4D4E4F4G4c3f3a2d2g2\nb\n2a\nb\ne\n")
    assert data is not None
    assert data.piece.tuning == "c2d2e2f2g2c3f3a3d4g4"


def test_baroque_and_guitar_presets_are_scientific_pitch() -> None:
    assert tuning_preset("dminor") == "a1b-1c2d2e2f2g2a2d3f3a3d4f4"
    assert tuning_preset("sharp") == "c2d2e2f+2g2a2d3g3b3d4f+4"
    assert tuning_preset("flat") == "c2d2e-2f2g2a2d3g3a+3d4f4"
    assert tuning_preset("guitar") == "e2a2d3f+3b3e4"


def test_a_short_tuning_does_not_hide_courses_that_have_notes(tmp_path: Path) -> None:
    path = tmp_path / "short.tab"
    path.write_text("-tuning g4c3f3a2d2g2\nb\n2a     /a\nb\ne\n", encoding="utf-8")

    state = init_state(str(path), config_path=str(tmp_path / "config.toml"))

    assert state.piece.strings == 8


def test_bass_courses_and_rests_survive_save_and_reopen(tmp_path: Path) -> None:
    source = tmp_path / "source.tab"
    source.write_text("-tuning C4D4E4F4G4c3f3a2d2g2\nb\n2a     /a\nR2\n2b     ///c\nb\ne\n", encoding="utf-8")
    state = init_state(str(source), config_path=str(tmp_path / "config.toml"))
    target = tmp_path / "saved.tab"

    assert cmd_write(state, str(target))
    reopened = init_state(str(target), config_path=str(tmp_path / "config.toml"))

    def events(piece: Piece) -> list[tuple[int, list[tuple[int, int]]]]:
        return [(c.note_type, [(n.string, n.fret) for n in c.notes]) for c in piece.bars[0].chords]

    assert events(reopened.piece) == events(state.piece) == [(6, [(1, 0), (8, 0)]), (6, []), (6, [(1, 1), (10, 2)])]
    assert reopened.piece.tuning == state.piece.tuning == "c2d2e2f2g2c3f3a3d4g4"
