"""Writing `.tab` in the original `tab` program's syntax; see docs/tab-format.md."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from oud.exports.export_tab import TabExportError, export_tab
from oud.importers.tab import parse_tab_text_data
from petrucci.core.model import Bar, Chord, Note, Piece

QUARTER = 4
EIGHTH = 5


def _chord(note_type: int, *notes: tuple[int, int], dotted: bool = False) -> Chord:
    return Chord(note_type, dotted, None, [Note(course, fret, 0) for course, fret in notes])


def _export(*chords: Chord, style: str = "french", strings: int = 6, time_sig: str = "4/4", tuning: str = "") -> str:
    piece = Piece(title="T", bars=[Bar(chords=list(chords), time_sig=time_sig)], strings=strings, style=style)
    piece.tuning = tuning or None
    return export_tab(piece, {}, {}, 16, settings={"style": style})


def _chord_lines(text: str) -> list[str]:
    body = text.split("\nb\n", 1)[1]
    return [line for line in body.splitlines() if line and line[0] not in "bSe"]


def test_chord_lines_use_spaces_and_a_place_marker_never_dash_padding() -> None:
    text = _export(_chord(QUARTER, (1, 0)), _chord(QUARTER, (2, 2), (4, 1)), _chord(EIGHTH, (3, 3), dotted=True))

    assert _chord_lines(text) == ["0a", "0 c b", "1.  d"]
    assert "-C" not in text.splitlines()
    assert "% Generated by oud" not in text


def test_rests_are_rest_lines() -> None:
    assert _chord_lines(_export(_chord(QUARTER), _chord(EIGHTH, dotted=True))) == ["R0", "R1."]


def test_bass_courses_go_to_position_seven() -> None:
    text = _export(
        _chord(QUARTER, (1, 0), (7, 0)),
        _chord(QUARTER, (8, 2)),
        _chord(QUARTER, (10, 0)),
        _chord(QUARTER, (11, 0)),
        _chord(QUARTER, (7, 0), (9, 1)),
        strings=11,
    )

    assert _chord_lines(text) == ["0a     a", "0      /c", "0      ///a", "0      4", "0      a b"]


def test_high_french_frets() -> None:
    assert _chord_lines(_export(_chord(QUARTER, (1, 9), (2, 14), (3, 15)))) == ["0kpN15"]


def test_italian_digits_count_from_the_lowest_course() -> None:
    text = _export(_chord(QUARTER, (1, 3), (6, 0)), _chord(QUARTER, (6, 10)), _chord(QUARTER, (5, 12)), style="italian")

    assert _chord_lines(text) == ["00    3", "0-!x", "0 N12"]


def test_time_signatures() -> None:
    for meter, line in (("3/4", "S34"), ("12/8", "S12-8"), ("C", "SC"), ("C|", "Sc"), ("3", "S3")):
        assert line in _export(_chord(QUARTER, (1, 0)), time_sig=meter).splitlines()


def test_tuning_is_written_in_the_program_notation() -> None:
    text = _export(_chord(QUARTER, (1, 0)), tuning="g2c3f3a3d4g4")
    assert "-tuning g4c3f3a2d2g2" in text.splitlines()


def test_a_chord_that_cannot_be_written_is_refused() -> None:
    with pytest.raises(TabExportError):
        _export(_chord(QUARTER, (7, 0), (8, 0), (10, 0)), strings=10)


def test_export_reads_back_identically() -> None:
    for style in ("french", "italian"):
        chords = [
            _chord(QUARTER, (1, 0), (3, 2), (7, 0)),
            _chord(EIGHTH, (2, 10), (8, 3), dotted=True),
            _chord(EIGHTH),
            _chord(2, (6, 0), (10, 0)),
        ]
        text = _export(*chords, style=style, strings=10, time_sig="3/4", tuning="c2d2e2f2g2c3f3a3d4g4")
        data = parse_tab_text_data(text)
        assert data is not None
        bar = data.piece.bars[0]
        assert [(c.note_type, c.dotted, [(n.string, n.fret) for n in c.notes]) for c in bar.chords] == [
            (c.note_type, c.dotted, [(n.string, n.fret) for n in c.notes]) for c in chords
        ]
        assert bar.time_sig == "3/4"
        assert data.piece.tuning == "c2d2e2f2g2c3f3a3d4g4"
        assert data.piece.style == style


@pytest.mark.tab_program
def test_the_original_program_reads_oud_output(tmp_path: Path) -> None:
    program = os.environ.get("TAB_PROGRAM", "")
    if not program:
        pytest.skip("set TAB_PROGRAM to a built `tab` binary (github.com/mandovinnie/Lute-Tab)")
    source = tmp_path / "out.tab"
    source.write_text(
        _export(_chord(QUARTER, (2, 0)), _chord(QUARTER, (1, 0), (8, 2)), _chord(QUARTER), strings=8),
        encoding="utf-8",
    )
    # The binary is the developer's own build named in TAB_PROGRAM, run without a shell.
    result = subprocess.run(  # noqa: S603
        [program, "-v", str(source), "-o", str(tmp_path / "out.ps")],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
        env={**os.environ, "TABFONTS": str(Path(program).parent)},
    )
    parsed = [line.removeprefix("main: ").rstrip() for line in result.stdout.splitlines() if line.startswith("main: ")]
    chords = [line for line in parsed if line and line[0] in "0R"]

    assert chords == ["0- a", "0-a     c", "0R"]
    assert "+-      /" in parsed


def _piece_of(*bars: Bar) -> Piece:
    return Piece(title="T", bars=list(bars), strings=6, style="french")


def _body(piece: Piece) -> list[str]:
    lines = export_tab(piece, {}, {}, 16, settings={"style": "french", "time": "4/4"}).splitlines()
    return lines[lines.index("b") :]


def test_systems_open_with_a_barline_and_end_at_blank_lines() -> None:
    bars = [Bar(chords=[_chord(QUARTER, (1, fret))]) for fret in range(3)]
    bars[0].time_sig = "4/4"
    bars[1].system_break = True

    assert _body(_piece_of(*bars)) == ["b", "S44", "0a", "b", "0b", "b", "", "b", "0c", "b", "e"]


def test_pieces_without_system_breaks_get_one_every_four_bars() -> None:
    body = _body(_piece_of(*[Bar(chords=[_chord(QUARTER, (1, 0))]) for _ in range(6)]))
    assert body.count("") == 1
    assert body.index("") == 1 + 4 * 2 + 1  # opening b, four bars of (chord, b), the S line


def test_meter_lines_only_where_needed() -> None:
    bars = [
        Bar(chords=[_chord(QUARTER, (1, 0))], time_sig="3/4"),
        Bar(chords=[_chord(QUARTER, (1, 0))], time_sig="3/4"),
        Bar(chords=[_chord(QUARTER, (1, 0))]),
        Bar(),
        Bar(chords=[_chord(QUARTER, (1, 0))], time_sig="2/4"),
    ]
    body = _body(_piece_of(*bars))
    assert [line for line in body if line.startswith("S")] == ["S34", "S34", "S24"]

    data = parse_tab_text_data("\n".join(["% Written by oud", "", *body]) + "\n")
    assert data is not None
    assert len(data.piece.bars) == len(bars)
    assert [bar.time_sig for bar in data.piece.bars] == ["3/4", None, None, "3/4", "2/4"]


def test_blank_lines_are_system_breaks_in_original_files_only() -> None:
    data = parse_tab_text_data("b\n0a\nb\n\nb\n0b\nb\n0c\nb\ne\n")
    assert data is not None
    assert [bar.system_break for bar in data.piece.bars] == [True, False, False]

    legacy = parse_tab_text_data("% Generated by oud\nb\n0a-----\n\nb\n0b-----\n\ne\n")
    assert legacy is not None
    assert [bar.system_break for bar in legacy.piece.bars] == [False, False]


@pytest.mark.parametrize(
    "path",
    sorted([*Path("examples").glob("*.tab"), *Path("tests/fixtures").glob("**/*.tab")]),
    ids=str,
)
def test_saving_is_idempotent_after_the_first_save(path: Path, tmp_path: Path) -> None:
    from oud.editor.services.bootstrap import init_state  # noqa: PLC0415
    from oud.editor.services.io.files import cmd_write  # noqa: PLC0415

    config = str(tmp_path / "config.toml")
    first, second = tmp_path / "first.tab", tmp_path / "second.tab"
    assert cmd_write(init_state(str(path), config_path=config), str(first))
    assert cmd_write(init_state(str(first), config_path=config), str(second))

    assert second.read_text(encoding="utf-8") == first.read_text(encoding="utf-8")
