from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_manpage_source_and_generated_page_are_tracked() -> None:
    source = ROOT / "man/oud.1.scd"
    generated = ROOT / "man/oud.1"

    assert source.read_text(encoding="utf-8").startswith("oud(1)")
    assert generated.read_text(encoding="utf-8").startswith(r".\" Generated by scdoc")
