from oud.core.tab_parser import load_tab, load_tab_data


def test_load_tab_simple(tmp_path) -> None:
    content = "{Title}\n{Author}\n\nb\n0ca\n1 d \nb\n"
    path = tmp_path / "simple.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.title == "Title"
    assert piece.author == "Author"
    assert len(piece.bars) == 1
    assert len(piece.bars[0].chords) == 2


def test_load_tab_data_cripps_format(tmp_path) -> None:
    content = "\n".join(
        [
            "% Generated by oud",
            "-C",
            "-tuning g2c3f3a3d4g4",
            "{Title/Composer}",
            "{Author}",
            "",
            "b",
            "Sc",
            "0a-----",
            "",
            "e",
        ],
    )
    path = tmp_path / "export.tab"
    path.write_text(content, encoding="utf-8")
    parsed = load_tab_data(str(path))
    assert parsed is not None
    assert parsed.piece.title == "Title"
    assert parsed.piece.composer == "Composer"
    assert parsed.piece.author == "Author"
    assert parsed.piece.tuning == "g2c3f3a3d4g4"
    assert parsed.piece.bars


def test_parse_french_extended_letters(tmp_path) -> None:
    content = "\n".join(
        [
            "{Test}",
            "b",
            "0qrst--",
            "e",
        ],
    )
    path = tmp_path / "extended.tab"
    path.write_text(content, encoding="utf-8")
    piece = load_tab(str(path))
    assert piece.bars
    notes = piece.bars[0].chords[0].notes
    assert [note.fret for note in notes[:4]] == [15, 16, 17, 18]
