from __future__ import annotations

from petrucci.rendering.primitives.helpers import safe_addstr
from petrucci.rendering.staff.grid import record_cursor_display_map, render_staff_grid
from petrucci.rendering.staff.playback import PlaybackOverlayCache, _playback_overlay_ops_for_bar
from petrucci.rendering.staff.vocal_rows import render_vocal_rows
from petrucci.terminal.canvas.screen import Screen


def _render_staff_and_playback(
    stdscr: Screen,
    *,
    piece,
    bar,
    abs_bar: int,
    ann_cells: list[str],
    ann_target_rows: list[int],
    bar_width: int,
    bar_x: int,
    barline: str,
    barpad: int,
    cells: list[list[str]],
    cursor_bar: int,
    cursor_col: int,
    cursor_display_maps: dict[int, list[int]] | None,
    cursor_string: int,
    display_width: int,
    draw_pad: int,
    effective_playback_markers: list[tuple[int, int]],
    grid_map: list[int],
    grid_width: int,
    highlights: set[tuple[int, int, int]],
    lyric_row_offsets: tuple[int, ...],
    melody_rows_count: int,
    orn_cells: list[str],
    orn_target_rows: list[int],
    playback_cache: PlaybackOverlayCache | None,
    positions: list[tuple[int, int, bool]],
    repeat_left: bool,
    repeat_right: bool,
    repeat_rows: set[int],
    row_start: int,
    rows: dict[str, int | None],
    scale_bar: bool,
    settings: dict[str, str],
    show_time_sig_here: bool,
    sig_label: str,
    src_to_dest: dict[int, int],
    style: str,
    system_display_strings: int,
    system_visual_indices: list[int],
    text_onset_cols: list[int],
    time_value: str,
    tuning_pitches: list[int],
    width: int,
) -> None:
    record_cursor_display_map(
        cursor_display_maps,
        bar=bar,
        abs_bar=abs_bar,
        bar_width=bar_width,
        grid_width=grid_width,
        grid_map=grid_map,
    )
    rendered_staff_rows = render_staff_grid(
        stdscr,
        bar=bar,
        abs_bar=abs_bar,
        ann_cells=ann_cells,
        ann_target_rows=ann_target_rows,
        bar_width=bar_width,
        bar_x=bar_x,
        barline=barline,
        barpad=barpad,
        cells=cells,
        cursor_bar=cursor_bar,
        cursor_col=cursor_col,
        cursor_string=cursor_string,
        display_width=display_width,
        draw_pad=draw_pad,
        grid_map=grid_map,
        grid_width=grid_width,
        highlights=highlights,
        orn_cells=orn_cells,
        orn_target_rows=orn_target_rows,
        repeat_left=repeat_left,
        repeat_right=repeat_right,
        repeat_rows=repeat_rows,
        row_start=row_start,
        rows=rows,
        scale_bar=scale_bar,
        settings=settings,
        show_time_sig_here=show_time_sig_here,
        sig_label=sig_label,
        src_to_dest=src_to_dest,
        style=style,
        system_display_strings=system_display_strings,
        system_visual_indices=system_visual_indices,
        time_value=time_value,
        width=width,
    )
    vocal = render_vocal_rows(
        stdscr,
        piece=piece,
        bar=bar,
        abs_bar=abs_bar,
        bar_x=bar_x,
        barline=barline,
        display_width=display_width,
        draw_pad=draw_pad,
        lyric_row_offsets=lyric_row_offsets,
        melody_rows_count=melody_rows_count,
        row_start=row_start,
        rows=rows,
        settings=settings,
        text_onset_cols=text_onset_cols,
        tuning_pitches=tuning_pitches,
        width=width,
    )
    _render_playback(
        stdscr,
        bar=bar,
        abs_bar=abs_bar,
        bar_width=bar_width,
        bar_x=bar_x,
        display_width=display_width,
        draw_pad=draw_pad,
        effective_playback_markers=effective_playback_markers,
        grid_width=grid_width,
        playback_cache=playback_cache,
        positions=positions,
        rendered_staff_rows=rendered_staff_rows,
        row_start=row_start,
        rows=rows,
        src_to_dest=src_to_dest,
        system_display_strings=system_display_strings,
        system_visual_indices=system_visual_indices,
        tuning_pitches=tuning_pitches,
        melody_row_base=vocal.melody_row_base,
        vocal_onset_cols=vocal.onset_cols,
        rendered_melody_rows=vocal.melody_rows,
    )


def _render_playback(
    stdscr: Screen,
    *,
    bar,
    abs_bar: int,
    bar_width: int,
    bar_x: int,
    display_width: int,
    draw_pad: int,
    effective_playback_markers: list[tuple[int, int]],
    grid_width: int,
    playback_cache: PlaybackOverlayCache | None,
    positions: list[tuple[int, int, bool]],
    rendered_staff_rows: list[str],
    row_start: int,
    rows: dict[str, int | None],
    src_to_dest: dict[int, int],
    system_display_strings: int,
    system_visual_indices: list[int],
    tuning_pitches: list[int],
    melody_row_base: int | None,
    vocal_onset_cols: list[int],
    rendered_melody_rows: list[str] | None,
) -> None:
    def operations(playback_col: int) -> list[tuple[int, int, str, int]]:
        return _playback_overlay_ops_for_bar(
            bar=bar,
            playback_col=playback_col,
            bar_width=bar_width,
            grid_width=grid_width,
            positions=positions,
            src_to_dest=src_to_dest,
            draw_pad=draw_pad,
            display_width=display_width,
            row_start=row_start,
            rows=rows,
            system_display_strings=system_display_strings,
            system_visual_indices=system_visual_indices,
            rendered_staff_rows=rendered_staff_rows,
            bar_x=bar_x,
            tuning_pitches=tuning_pitches,
            melody_row_base=melody_row_base,
            vocal_onset_cols=vocal_onset_cols,
            rendered_melody_rows=rendered_melody_rows,
        )

    if playback_cache is not None:
        playback_limit = len(bar.chords) if bar.chords else bar_width
        for overlay_col in range(max(0, playback_limit)):
            playback_cache[(abs_bar, overlay_col)] = operations(overlay_col)
    playback_cols = [column for marker_bar, column in effective_playback_markers if marker_bar == abs_bar]
    for marker_col in playback_cols:
        for y, x, text, attr in operations(marker_col):
            safe_addstr(stdscr, y, x, text, attr)
