from __future__ import annotations

HELP_LINES = [
    "HELP",
    "",
    "FIRST SCORE",
    "Open/create  oud [FILE] / oud       Open here  :e FILE",
    "Enter note   i, type fret a-t or 0-9, then Esc",
    "Undo         u                       Save       :w [FILE.tab]",
    "Quit         :q                      Discard    :q!",
    "",
    "NAVIGATION                              EDITING",
    "Up   k / w / ^P / Up                    Insert   i / Enter",
    "Down j / s / ^N / Down                  Replace  r (one)",
    "Left h / a / ^B / Left                  Delete   x / [count]x",
    "Right l / d / ^F / Right                Clear    Space (insert)",
    "Row  K/J or W/S    Scroll PgUp/PgDn      Yank     yy  Paste  p",
    "Viewer system K/J or W/S; section/page [ / ] (cursor stays put)",
    "Bar  w/b or ,/.                          Delete  dd / Delete",
    "Undo u/^Z  Redo ^R/^Y                    Bar     o/O  +/-",
    "Top  gg / g                             Help    ? / F1 / gh",
    "Info I / gi                              Flags f (cycle style)",
    "Search * / # / n / N                     Marks   m{a}  'a  `a",
    "Match %                                  Play    M",
    "Visual v / V                              Yank rows y",
    "Add  gj (bass string)",
    "Plugins gp or :plugins   Reload gr",
    "Flags f (cycle style)                   Letters F (c)",
    "End  G / $                              Command : / Search /",
    "",
    "INSERT MODE",
    "Frets: french a-t (no j), italian 0-9/x",
    "Italian multi-fret: ,10 .. ,24 (comma + two digits)",
    "Bass shorthand: /a, //a, ///a (adds 7th/8th/9th course)",
    "Durations: 1 2 4 8 6 3 (french) or Ctrl+1..7 / ;1..7 (italian)",
    "Barline: | sets thin barline",
    "Esc returns to normal",
    "Mixed/duet FT3 scores are view-only because non-TAB layers cannot round-trip",
    "Viewer staff focus: j/k (or w/s in casual keys) cycles visible staves",
    "Viewer mode: :set scoreview=score|staff (focus and cursor are preserved)",
    "",
    "COMMANDS",
    ":w [path]        write .tab       First imported/new write prompts for Save As",
    "FT3 edits save to a sibling .tab file; the downloaded FT3 is never overwritten",
    ":wa [path]        export ascii     :wascii [path]    export ascii",
    ":wq/:x           write + quit     :q!               quit without save",
    ":e <path>        open             :source [path]    view file with less",
    ":help             open this help in less",
    ":time <sig>      set time sig     :verify           check measure length",
    ":info             show info page  :notes            show notes page",
    ":ack              dismiss persistent notice",
    ":undo             undo             :redo             redo",
    ":title <text>     set title        :author <text>     set author",
    ":subtitle <text>  set subtitle     :composer <text>   set composer",
    ":footnote <text>  set footnote     :header            insert header template",
    ":midi [path]     export midi      :play [bar] [tempo] play from bar",
    ":lilypond [path] export lilypond  :musicxml [path] export musicxml/mxl",
    ":pdf              compile pdf (P)",
    ":hide             toggle the bottom status panel",
    ":midicmd [path]  show midi command",
    ":bar add|before|after|del         :barline thin|thick|double|hidden|pale",
    ":vocal clear      remove imported melody/lyrics layer",
    (
        ":repeat none|start|end|dots|both|dc|ds|fine|coda|tocoda|"
        "dcalfine|dcalcoda|dsalfine|dsalcoda   :ending clear|1|1,2"
    ),
    ":orn <char>|clear               :highlight on/off",
    ":annot <text>|clear",
    ":slur start/end/clear             :tie start/end/clear",
    ":hold start/end/clear             :tuplet 2..9|clear",
    ":arpeggio on/off/toggle           :separee on/off/toggle",
    ":transpose <int>  :retune <tuning/preset>  :courseshift up|down",
    (
        ":set style=... strings=... tuning=... tuninglabels=... "
        "flagstyle=... flagstems=... dotplacement=afterflag|afterstem time=... (or auto)"
    ),
    ":set keys=vim|vim+arrows|casual|casual+arrows",
    ":set contrast=normal|high   :set theme=auto|dark|light (or :dark / :light)",
    (
        ":set spacing=... barsperline=... maxbars=... maxchords=... chordwrap=... bargap=... "
        "linelen=... staffthick=... fontstyle=..."
    ),
    ":set flagredundant=on|off",
    (":set layout=packed|spread|auto|stretch justify=stretch|center|compact|smart|edge showtuning=on|off"),
    ":set key=... countdots=on/off grid=on/off",
    ":set lute|guitar (preset metasettings)",
    ":set measures=start|system|every|five measuresstep=... (step used with every)",
    ":set italianorient=normal|reverse italianmultifret=on|off viewinvert=on|off",
    ":set frenchc=normal|alt",
    ":set midipatch=... midivocalpatch=... midigate=... soundfont=... tempo=...",
    ":set showmelody=on|off showlyrics=on|off vocalpos=top|bottom",
    ":set lyricmode=first|current|all lyricverse=N (current selects N)",
    ":set scoreview=score|staff",
    ":set playverses=once|all playbackscroll=on|off",
    ":set charstyle=... title=... author=... composer=...",
    ":tool reflow|gridflags|flagstyle|comments",
]


def help_lines() -> list[str]:
    return list(HELP_LINES)
