"""Chord lines and tuning of the original `tab` program format.

Rules follow the program's reader (`getsys.cc`, `score.cc`, version 4.3.108);
`docs/tab-format.md` summarises them. Files that Oud wrote before it followed
the program use their own dialect: every character after the flag is one
course, `-` pads empty courses, and `-tuning` is scientific pitch.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from itertools import pairwise

from petrucci.core.model import Note

OUD_HEADER = "% Generated by oud"
# First line of files Oud writes in the program's syntax (not a dialect marker).
WRITTEN_HEADER = "% Written by oud"
ITALIAN_SETTING = "$numstyle=italian"
MILAN_OPTION = "-milan"
_ITALIAN_OPTIONS = frozenset({"-i", "-O", "-x", "-milan"})
_CHORD_FLAGS = frozenset("0123456WwLx#tY")

POSITIONS = 9
TREBLE_POSITIONS = 6
BASS_POSITION = 7

# Characters that may follow the flag without being the first course.
FLAG_MODIFIERS = frozenset("!-#*|.tWQ@B&")
_DOTTING_MODIFIERS = frozenset(".@*")
# Symbols printed before the next note; they take no position.
_PREFIX_SYMBOLS = frozenset("x`Q#$,='^@_*%")
_FRENCH_GLYPH_VARIANTS = {"D": "d", "E": "e", "F": "f", "G": "g", "H": "h", "I": "i"}
_LETTER_SKIP_FROM = 9  # the program counts j and k both as fret 9
_ITALIAN_LETTERS = {"x": 10, "y": 11, "z": 0}
_HIGH_FRET_DIGITS = 2
_OCTAL_ESCAPE_DIGITS = 3
_LEGACY_LETTERS = "abcdefghiklmnopqrst"
_LEGACY_ALT_C = "r"
_LEGACY_ALT_C_FRET = 2
_LEGACY_SYMBOLS = {"x": 10, "E": 4}


class TabDialect(StrEnum):
    ORIGINAL = "original"
    OUD_LEGACY = "oud-legacy"


@dataclass(frozen=True, slots=True)
class TabSyntax:
    dialect: TabDialect = TabDialect.ORIGINAL
    milan: bool = False
    italian: bool = False


@dataclass(frozen=True, slots=True)
class _Position:
    char: str = " "
    slashes: int = 0
    fret: int | None = None


_EMPTY = _Position()


@dataclass(frozen=True, slots=True)
class ChordPositions:
    """The note positions of one chord line; ``rest`` marks an `R` among them."""

    positions: tuple[_Position, ...]
    rest: bool = False


def detect_syntax(lines: list[str]) -> TabSyntax:
    first = next((line.strip() for line in lines if line.strip()), "")
    dialect = TabDialect.OUD_LEGACY if first == OUD_HEADER else TabDialect.ORIGINAL
    options = {token for line in lines if line.startswith("-") for token in line.split()}
    italian = bool(options & _ITALIAN_OPTIONS) or any(line.strip() == ITALIAN_SETTING for line in lines)
    return TabSyntax(dialect, MILAN_OPTION in options, italian or _digits_without_letters(lines))


def _digits_without_letters(lines: list[str]) -> bool:
    # `t` and `#` lines carry the flag as their second character.
    bodies = "".join(line[2 if line[:1] in "t#" else 1 :] for line in lines if line[:1] in _CHORD_FLAGS)
    has_letter = any("a" <= char <= "p" for char in bodies)
    return not has_letter and any(char.isdigit() for char in bodies)


@dataclass(frozen=True, slots=True)
class FlagModifier:
    text: str
    dotted: bool = False
    grid: bool = False


def split_flag(payload: str, syntax: TabSyntax) -> FlagModifier:
    """Strip the modifier that may follow the flag; the rest is the note text."""

    if syntax.dialect is TabDialect.OUD_LEGACY:
        text = payload.removeprefix("!")
        dotted = text.startswith(".")
        text = text.removeprefix(".")
        return FlagModifier(text.removeprefix("#"), dotted, text.startswith("#"))
    if not payload or payload[0] not in FLAG_MODIFIERS:
        return FlagModifier(payload)
    modifier = payload[0]
    text = payload[2:] if modifier == "&" else payload[1:]
    return FlagModifier(text, modifier in _DOTTING_MODIFIERS, modifier == "#")


def read_positions(text: str, syntax: TabSyntax) -> ChordPositions:
    if syntax.dialect is TabDialect.OUD_LEGACY:
        return ChordPositions(tuple(_Position(char) for char in text.rstrip()))
    reader = _PositionReader(text)
    return reader.read()


class _PositionReader:
    def __init__(self, text: str) -> None:
        self.text = text
        self.index = 0
        self.slashes = 0
        self.positions: list[_Position] = []
        self.rest = False

    def read(self) -> ChordPositions:
        while len(self.positions) < POSITIONS and self.index < len(self.text):
            if not self._step(self.text[self.index]):
                break
        return ChordPositions(tuple(self.positions), self.rest)

    def _peek(self, offset: int = 1) -> str:
        at = self.index + offset
        return self.text[at] if at < len(self.text) else ""

    def _step(self, char: str) -> bool:
        if char in "MT\t\n":
            return False
        if char == "R":
            self.rest = True
            return False
        if self._consume_prefix(char):
            return True
        self._consume_position(char)
        self._consume_postfix()
        return True

    def _consume_prefix(self, char: str) -> bool:
        if char == "/" and self._peek() not in (" ", ""):
            count = len(self.text[self.index :]) - len(self.text[self.index :].lstrip("/"))
            self.slashes, self.index = count, self.index + count
            return True
        if char in "st" and len(self.positions) >= TREBLE_POSITIONS:
            self.slashes, self.index = (2 if char == "s" else 3), self.index + 1
            return True
        skip = self._prefix_width(char)
        self.index += skip
        return skip > 0

    def _prefix_width(self, char: str) -> int:
        if char in _PREFIX_SYMBOLS:
            return 1
        if char == "+":
            return 2 if self._peek() == "*" else 1
        if char == '"':
            return 2
        if char == "\\" and self._peek() != "\\":
            return 2
        if char == "<":
            return self._special_width()
        return 0

    def _special_width(self) -> int:
        if self._peek() != "!":
            return 1
        end = self.text.find(">", self.index)
        return (end - self.index + 1) if end >= 0 else len(self.text) - self.index

    def _consume_position(self, char: str) -> None:
        width, position = 1, _Position(char, self.slashes)
        if char == "N" and self.text[self.index + 1 : self.index + 3].isdigit():
            width = 1 + _HIGH_FRET_DIGITS
            position = _Position(char, self.slashes, int(self.text[self.index + 1 : self.index + width]))
        elif char == "!":
            width, position = self._escape()
        elif char in "]|\\" and self._peek() in ("vw" if char == "]" else char):
            width = 2
        self.positions.append(position)
        self.slashes = 0
        self.index += width

    def _escape(self) -> tuple[int, _Position]:
        literal = self._peek()
        if literal == "0":
            return 2 + _OCTAL_ESCAPE_DIGITS, _Position("!")
        return 2, _Position(literal or " ")

    def _consume_postfix(self) -> None:
        if self._peek(0) != "&":
            return
        self.index += 2
        if self.text[self.index - 1 : self.index] == "]" and self._peek(0) in ("v", "w"):
            self.index += 1


def position_notes(chord: ChordPositions, syntax: TabSyntax) -> list[Note]:
    notes: list[Note] = []
    for index, position in enumerate(chord.positions, start=1):
        if syntax.dialect is TabDialect.OUD_LEGACY:
            fret = _legacy_fret(position.char, chord)
            course = index
        else:
            course, fret = _original_note(index, position, syntax)
        if fret is not None:
            notes.append(Note(string=course, fret=fret, raw_pos=0))
    return sorted(notes, key=lambda note: note.string)


def _legacy_fret(char: str, chord: ChordPositions) -> int | None:
    chars = {position.char for position in chord.positions}
    if char == _LEGACY_ALT_C and not chars & set("qst"):
        return _LEGACY_ALT_C_FRET
    if char in _LEGACY_LETTERS:
        return _LEGACY_LETTERS.index(char)
    if char.isdigit():
        return int(char)
    return _LEGACY_SYMBOLS.get(char)


def _original_note(index: int, position: _Position, syntax: TabSyntax) -> tuple[int, int | None]:
    char = position.char
    if position.fret is not None:
        return (_italian_course(index, syntax) if syntax.italian else index), position.fret
    if index == BASS_POSITION and char in "456":
        return BASS_POSITION + int(char), 0
    if char.isdigit() or char in _ITALIAN_LETTERS:
        fret = int(char) if char.isdigit() else _ITALIAN_LETTERS[char]
        return _italian_course(index, syntax), fret
    letter = _FRENCH_GLYPH_VARIANTS.get(char, char)
    if not "a" <= letter <= "p":
        return index, None
    fret = ord(letter) - ord("a")
    fret -= fret > _LETTER_SKIP_FROM
    course = index + position.slashes if index == BASS_POSITION else index
    return course, fret


def _italian_course(index: int, syntax: TabSyntax) -> int:
    # Italian tablature puts the lowest course on the top line.
    if syntax.milan or index > TREBLE_POSITIONS:
        return index
    return TREBLE_POSITIONS + 1 - index


def read_tuning(text: str) -> str:
    """`-tuning` as scientific pitch, bass course first.

    The program counts octaves downward, so its digits never rise from the bass
    to course 1; scientific pitch never falls. Files that Oud or other tools
    wrote in scientific pitch are therefore kept as they are.
    """

    octaves = [int(digit) for digit in "".join(char if char.isdigit() else " " for char in text).split()]
    falling = any(later < earlier for earlier, later in pairwise(octaves))
    rising = any(later > earlier for earlier, later in pairwise(octaves))
    return tuning_to_scientific(text) if falling and not rising else text


def tuning_to_scientific(text: str) -> str:
    """Convert the program's `-tuning` notation (octaves counted downward from a) to scientific pitch."""

    parts: list[str] = []
    index = 0
    while index < len(text):
        letter = text[index].lower()
        index += 1
        if not "a" <= letter <= "g":
            continue
        accidental = text[index] if index < len(text) and text[index] in "+-" else ""
        index += len(accidental)
        digits = ""
        while index < len(text) and text[index].isdigit():
            digits += text[index]
            index += 1
        octave = int(digits) if digits else _PROGRAM_DEFAULT_OCTAVE
        scientific = (5 if letter in "ab" else 6) - octave
        parts.append(f"{letter}{accidental}{scientific}")
    return "".join(parts)


_PROGRAM_DEFAULT_OCTAVE = 3
_SCIENTIFIC_DEFAULT_OCTAVE = 3
_PROGRAM_OCTAVES = range(5)  # the program reads octave digits 0-4 only
_SHARPS = "+#"
_FLATS = "-b"


def scientific_to_tuning(text: str) -> str | None:
    """Scientific pitch (bass first) in the program's `-tuning` notation; ``None`` if it has no such spelling."""

    parts: list[str] = []
    index = 0
    while index < len(text):
        letter = text[index].lower()
        index += 1
        if not "a" <= letter <= "g":
            continue
        accidental = ""
        if index < len(text) and text[index] in _SHARPS + _FLATS:
            accidental = "+" if text[index] in _SHARPS else "-"
            index += 1
        digits = ""
        while index < len(text) and text[index].isdigit():
            digits += text[index]
            index += 1
        octave = (5 if letter in "ab" else 6) - (int(digits) if digits else _SCIENTIFIC_DEFAULT_OCTAVE)
        if octave not in _PROGRAM_OCTAVES:
            return None
        parts.append(f"{letter}{accidental}{octave}")
    return "".join(parts) or None


def read_time_signature(line: str, syntax: TabSyntax) -> str | None:
    """Meter of an `S` line: `SC` is C, `Sc` cut C, `S34` and `S12-8` are fractions."""

    text = line.strip()[1:]
    if not text:
        return None
    if syntax.dialect is TabDialect.OUD_LEGACY:
        return {"c": "C", "c|": "C|"}.get(text, text)
    if text in ("C", "c"):
        return "C" if text == "C" else "C|"
    if "-" in text:
        return text.replace("-", "/", 1)
    if len(text) == 2 and text.isdigit():  # noqa: PLR2004 - one numerator and one denominator digit
        return f"{text[0]}/{text[1]}"
    return text
