from __future__ import annotations

from petrucci.render_chord_rhythm import render_chord_rhythm
from petrucci.render_grid_rhythm import render_grid_rhythm
from petrucci.render_rhythm_types import RhythmRenderContext
from petrucci.screen import Screen


def _render_rhythm_rows(
    stdscr: Screen,
    *,
    bar,
    abs_bar: int,
    bar_width: int,
    bar_x: int,
    barpad: int,
    beats: int,
    cells: list[list[str]],
    chord_positions_all: list[tuple[int, int, bool]],
    cursor_bar: int,
    cursor_col: int,
    default_duration: int,
    display_width: int,
    dotted: set[tuple[int, int]],
    draw_pad: int,
    durations: dict[tuple[int, int, int], int],
    french_c: str,
    fretlabelmode: str,
    grid_width: int,
    hide_redundant: bool,
    overrides: dict[tuple[int, int, int], str],
    pad: int,
    row_start: int,
    rows: dict[str, int | None],
    scale_bar: bool,
    settings: dict[str, str],
    show_dur: bool,
    spacing_fill: str,
    spacing_mode: str,
    style: str,
    style_policy,
    total_strings: int,
    ann_cells: list[str],
    slur_cells: list[str],
    tie_cells: list[str],
    hold_cells: list[str],
    gliss_cells: list[str],
    tuplet_cells: list[str],
    scaled_slur_row: list[str] | None,
    scaled_tie_row: list[str] | None,
    scaled_hold_row: list[str] | None,
    scaled_gliss_row: list[str] | None,
    scaled_tuplet_row: list[str] | None,
) -> tuple[list[tuple[int, int, bool]], dict[int, int], list[int], list[int]]:
    context = RhythmRenderContext(
        stdscr=stdscr,
        bar=bar,
        abs_bar=abs_bar,
        bar_width=bar_width,
        bar_x=bar_x,
        barpad=barpad,
        beats=beats,
        cells=cells,
        chord_positions_all=chord_positions_all,
        cursor_bar=cursor_bar,
        cursor_col=cursor_col,
        default_duration=default_duration,
        display_width=display_width,
        dotted=dotted,
        draw_pad=draw_pad,
        durations=durations,
        french_c=french_c,
        fretlabelmode=fretlabelmode,
        grid_width=grid_width,
        hide_redundant=hide_redundant,
        overrides=overrides,
        pad=pad,
        row_start=row_start,
        rows=rows,
        scale_bar=scale_bar,
        settings=settings,
        show_dur=show_dur,
        spacing_fill=spacing_fill,
        spacing_mode=spacing_mode,
        style=style,
        style_policy=style_policy,
        total_strings=total_strings,
        ann_cells=ann_cells,
        slur_cells=slur_cells,
        tie_cells=tie_cells,
        hold_cells=hold_cells,
        gliss_cells=gliss_cells,
        tuplet_cells=tuplet_cells,
        scaled_slur_row=scaled_slur_row,
        scaled_tie_row=scaled_tie_row,
        scaled_hold_row=scaled_hold_row,
        scaled_gliss_row=scaled_gliss_row,
        scaled_tuplet_row=scaled_tuplet_row,
    )
    result = render_chord_rhythm(context) if bar.chords else render_grid_rhythm(context)
    return result.positions, result.src_to_dest, result.grid_map, result.text_onset_cols
